### ISSUE TITLE
Extra Info from BAXI app

### ISSUE THREAD

**Issue by alessandrobenevelli** [vipial1/BAXI_thermostat#6]
Hello, in the BAXI app you can find additional information on the status of the boiler:
- external temperature (if external probe is present)
- water pressure
- system temperature

Would it be possible to add this information to the component as well?
Would it also be possible to show the status of the burner (on / off) as it appears on the boiler display?

Thank you

![Screenshot_2022-08-24-08-45-20-22_8aa8ff7c1275e8270f892ce16fd72cfa](https://user-images.githubusercontent.com/62119338/186377058-8236f75b-ea80-43d2-bf5f-7740018d5340.jpg)

**Comment by vipial1** [comment]
I have added water pressure information.
I can not add external temperature because I have not probe.
And for system temperature, I have not been able to find the endpoint for getting it. At fact, mine is showing always same temperature, so not sure if it is simply a hardcoded value...

Regarding the burner status, that info is not available from the mobile app, so I can not get it for HA neither.

Values has been added as extra attributes:
<img width="909" alt="Screenshot 2022-09-05 at 23 33 08" src="https://user-images.githubusercontent.com/4264467/188514305-f912a43a-070f-49fb-bbbe-577478aaef5e.png">
